# Generated by Django 5.1.6 on 2025-02-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
